MODEL (
  name trusted_zone.journeys_2022,
  kind INCREMENTAL_BY_TIME_RANGE (
    time_column start_datetime,
    batch_size 30
  ),
  start '2022-01-01 00:00:00+0100',
  end '2022-12-31 23:59:59+0100',
  grain '_id',
  tags ['trusted', 'journeys', '2022'],
);

SELECT
  _id,
  uuid,
  legacy_id,
  created_at,
  updated_at,
  operator_id,
  operator_name,
  operator_siret,
  operator_journey_id,
  operator_trip_id,
  operator_class::varchar AS operator_class,
  start_datetime,
  start_datetime_tz,
  ST_Point(start_position_x, start_position_y) AS start_position,
  start_h3_index::h3index AS start_h3_index,
  start_geo_code,
  end_datetime,
  end_datetime_tz,
  ST_Point(end_position_x, end_position_y) AS end_position,
  end_h3_index::h3index AS end_h3_index,
  end_geo_code,
  geo_errors::jsonb AS geo_errors,
  geo_updated_at,
  distance,
  duration,
  licence_plate,
  driver_identity_key,
  driver_operator_user_id,
  driver_phone,
  driver_phone_trunc,
  driver_id,
  driver_travelpass_name,
  driver_travelpass_user_id,
  driver_revenue,
  passenger_identity_key,
  passenger_operator_user_id,
  passenger_phone,
  passenger_phone_trunc,
  passenger_id,
  passenger_travelpass_name,
  passenger_travelpass_user_id,
  passenger_over_18,
  passenger_seats,
  passenger_contribution,
  passenger_payments::jsonb AS passenger_payments,
  operator_incentives_sirets,
  operator_incentives_amounts,
  operator_incentives_amount_total,
  operator_incentives::jsonb AS operator_incentives,
  campaign_incentives_amount_total,
  campaign_incentives_result_total,
  campaign_incentives::jsonb AS campaign_incentives,
  fraud_status,
  fraud_labels,
  anomaly_status,
  anomaly_labels,
  acquisition_status,
  status_updated_at,
  final_acquisition_status,
  valid_acquisition_status
FROM raw_zone.journeys_2022
WHERE start_datetime BETWEEN @start_ts AND @end_ts;

@create_index(@this_model, _id, 'name=journeys_2022_id_index');
@create_index(@this_model, start_datetime_tz, 'name=journeys_2022_start_datetime_tz_index');
@create_index(@this_model, start_h3_index, 'name=journeys_2022_start_h3_index_index');
@create_index(@this_model, end_h3_index, 'name=journeys_2022_end_h3_index_index');
