set dotenv-load := true

# Installe les dépendances
install:
    uv sync

# Lance l'API en développement (rechargement à chaud)
dev:
    uv run uvicorn api_datalake.main:app --reload --app-dir src --port 8081

# Lance l'API en production
serve port="8081":
    uv run uvicorn api_datalake.main:app --app-dir src --host 0.0.0.0 --port {{port}}

# Tests
test:
    uv run python -m pytest -q
