name: Issues cleanup

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "23 */12 * 1-6,9-12 *"

jobs:
  stale:
    name: Close stale issues and PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899 # v10.3.0
        with:
          stale-issue-message: "Ce ticket est marqué comme obsolète car cela fait 60 jours qu'il n'y a pas eu d'activité dessus. Retirez ce label ou ajoutez un commentaire sinon ce ticket sera fermé dans 5 jours."
          stale-pr-message: "Cette PR est marquée comme obsolète car cela fait 60 jours qu'il n'y a pas eu d'activité dessus. Retirez ce label ou ajoutez un commentaire sinon cette PR sera fermée dans 5 jours."
          close-issue-message: "Ce ticket a été fermé car cela fait 5 jours qu'il a été marqué comme obsolète sans activité"
          close-pr-message: "Cette PR a été fermée car cela fait 5 jours qu'elle a été marquée comme obsolète sans activité"
          days-before-stale: 60
          days-before-close: 5
          exempt-issue-labels: "keep"
          enable-statistics: false
          operations-per-run: 100
