name: Deploy API documentation
permissions:
  contents: read
on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - chore/update-techdoc
jobs:
  deploy-doc:
    name: Deploy
    runs-on: ubuntu-latest

    # add files here
    strategy:
      matrix:
        include:
          - doc: api
            version: v3.3
            token: BUMP_TOKEN_API
          - doc: api
            version: v3.2
            token: BUMP_TOKEN_API
          # - doc: api
          #   version: v3.1
          #   token: BUMP_TOKEN_API
          # - doc: api
          #   version: v3.0
          #   token: BUMP_TOKEN_API

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false

      - name: Verify OpenAPI files
        run: |
          file="api/specs/${{ matrix.doc }}-${{ matrix.version }}.yaml"
          if [ ! -f "$file" ]; then
            echo "Error: $file does not exist"
            exit 1
          fi

      - name: Validate OpenAPI syntax
        uses: swaggerexpert/swagger-editor-validate@264fd875d3c6e1bf65da1f0a63e095cbe41ffef3
        with:
          definition-file: api/specs/${{ matrix.doc }}-${{ matrix.version }}.yaml

      - name: Deploy
        uses: bump-sh/github-action@590e36a25548cb10a8efb1ca9e5b1e111ad67120
        with:
          doc: ${{ matrix.doc }}
          token: ${{ secrets[matrix.token] }}
          file: api/specs/${{ matrix.doc }}-${{ matrix.version }}.yaml
          branch: ${{ matrix.version }}
