name: Deploy backend images

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  release:
    types: [published]
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  tag: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}

jobs:
  build:
    name: Build ${{ matrix.name }}
    uses: ./.github/workflows/base-build-push-docker.yml
    with:
      name: ${{ matrix.name }}
      context: .
      tag: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
      dockerfile: ${{ matrix.dockerfile }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    strategy:
      matrix:
        name: ["api", "data"]
        include:
          - name: api
            dockerfile: "./docker/api/Dockerfile"
          - name: data
            dockerfile: "./docker/data/Dockerfile"
