name: Deploy API documentation

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy API documentation
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # List all versions of the API documentation to deploy
        version: [v3.3, v3.4]

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Verify OpenAPI files
        run: | # zizmor: ignore[template-injection]
          file="api/specs/api-${{ matrix.version }}.yaml"
          if [ ! -f "$file" ]; then
            echo "Error: $file does not exist"
            exit 1
          fi

      - name: Deploy
        uses: bump-sh/github-action@6aff793a699f2e3269de3124a7a3eb46e5ffb261 # v1.3.0
        with:
          doc: api
          token: ${{ secrets.BUMP_TOKEN_API }}
          file: api/specs/api-${{ matrix.version }}.yaml
          branch: ${{ matrix.version }}
