name: 'Deploy CMS'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'cms/**'

defaults:
  run:
    shell: bash

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.set_tag.outputs.value }}
    steps:
      - id: set_tag
        run: echo "value=$(date +'%F.%H%M')" >> $GITHUB_OUTPUT

  build:
    needs: tag
    name: Build cms
    uses: ./.github/workflows/base-build-push-docker.yml
    with:
      name: cms
      context: ./cms
      tag: ${{ needs.tag.outputs.value }}
      dockerfile: ./docker/cms/prod/Dockerfile 
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
