name: Deploy API documentation

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy API documentation
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # List all versions of the API documentation to deploy
        version: [v3.3, v3.4]

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: false

      - name: Verify OpenAPI files
        run: | # zizmor: ignore[template-injection]
          file="api/specs/api-${{ matrix.version }}.yaml"
          if [ ! -f "$file" ]; then
            echo "Error: $file does not exist"
            exit 1
          fi

      - name: Deploy
        uses: bump-sh/github-action@590e36a25548cb10a8efb1ca9e5b1e111ad67120
        with:
          doc: api
          token: ${{ secrets.BUMP_TOKEN_API }}
          file: api/specs/api-${{ matrix.version }}.yaml
          branch: ${{ matrix.version }}
