name: Deploy backend images

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-{{ matrix.name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  release:
    types: [published]
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  tag: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}

jobs:
  build:
    name: Build ${{ matrix.name }} image
    steps:
      - name: Build ${{ matrix.name }}
        uses: ./.github/actions/build-image
        with:
          name: ${{ matrix.name }}
          context: .
          tag: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
          dockerfile: ${{ matrix.dockerfile }}
        strategy:
          matrix:
            name: ["api", "data"]
            include:
              - name: api
                dockerfile: "./docker/api/Dockerfile"
              - name: data
                dockerfile: "./docker/data/Dockerfile"
