name: Deploy CMS image

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "cms/**"

defaults:
  run:
    shell: bash

jobs:
  tag:
    name: Set deployment tag
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.set_tag.outputs.value }}
    steps:
      - id: set_tag
        run: echo "value=$(date +'%F.%H%M')" >> $GITHUB_OUTPUT

  build:
    needs: tag
    name: Build cms
    uses: ./.github/actions/build-image
    with:
      name: cms
      context: ./cms
      tag: ${{ needs.tag.outputs.value }}
      dockerfile: ./docker/cms/prod/Dockerfile
