name: Deploy Notebooks (data)
description: Build and push a Python image for notebooks (data).

permissions:
  contents: read
  packages: write # zizmor: ignore[excessive-permissions]
  id-token: write # zizmor: ignore[excessive-permissions]
  attestations: write # zizmor: ignore[excessive-permissions]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "dbt/**"

jobs:
  tag:
    name: Set deployment tag
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.set_tag.outputs.value }}
    steps:
      - id: set_tag
        shell: bash
        run: echo "value=$(date +'%F.%H%M')" >> $GITHUB_OUTPUT
  build:
    name: Build and Push DATA Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: false
      - name: Build and Push DATA Docker Image
        uses: ./.github/actions/build-image
        with:
          name: data
          context: .
          tag: ${{ needs.tag.outputs.value }}
          dockerfile: ./docker/data/Dockerfile
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
