name: Quality

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-lint:
    name: (api) Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: false
      - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.lock') }}
      - uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb
        with:
          deno-version: v2.x
      - name: Run lint
        working-directory: ./api
        # FIXME
        continue-on-error: true
        run: deno lint

  api-unit:
    needs: [api-lint]
    name: (api) unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: false
      - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.lock') }}
      - uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb
        with:
          deno-version: v2.x
      - uses: taiki-e/install-action@5597bc27da443ba8bf9a3bc4e5459ea59177de42
        with:
          tool: just@1.44.1
      - name: Run unit test
        run: just cache && just ci_test_unit
        working-directory: api
        env:
          APP_POSTGRES_URL: postgres://
          APP_REDIS_URL: redis://

  api-integration:
    needs: [api-unit]
    name: (api) integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: false
      - name: Build stack
        uses: ./.github/actions/build-stack
      - name: Run integration tests
        working-directory: api
        run: deno test --quiet --no-check -A --unsafely-ignore-certificate-errors '**/*.integration.spec.ts'
        env:
          APP_CEE_PRIVATE_KEY_PATH: ${{ github.workspace }}/docker/api/certs/privateKey.pem
          APP_CEE_PUBLIC_KEY_PATH: ${{ github.workspace }}/docker/api/certs/publicKey.pem
          APP_JWT_SECRET: "integration-test"
          APP_MAIL_SMTP_URL: smtp://localhost:1025
          APP_POSTGRES_TIMEOUT: 120000
          APP_POSTGRES_URL: postgres://postgres:postgres@localhost:5432/test
          APP_REDIS_URL: redis://localhost:6379
          AWS_SECRET_ACCESS_KEY: minioadmin
          AWS_ACCESS_KEY_ID: minioadmin
          AWS_BUCKET_PREFIX: local-pdc
          AWS_ENDPOINT: https://s3.covoiturage.test
          AWS_REGION: fr-par
          INTEGRATION_MAILER_SMTP_HOST: localhost
          PRO_CONNECT_CLIENT_ID: ${{ secrets.PRO_CONNECT_CLIENT_ID }}
          PRO_CONNECT_CLIENT_SECRET: ${{ secrets.PRO_CONNECT_CLIENT_SECRET }}

  api-e2e:
    needs: [api-unit]
    name: (api) e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: false
      - name: Build stack
        uses: ./.github/actions/build-stack
      - name: Run e2e tests
        working-directory: api/e2e
        run: |
          deno test \
            --no-check \
            --quiet \
            --allow-net \
            --allow-env \
            --allow-import=cdn.esm.sh:443,deno.land:443,jsr.io:443 \
            --unsafely-ignore-certificate-errors
        env:
          APIE2E_API_URL: https://api.covoiturage.test

  front-audit:
    name: (front) audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: false

      - name: Install NodeJS
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: "24"

      - name: "Audit public site dependencies"
        run: npm audit --audit-level moderate && exit 0 || $([[ $? -ge 8 ]] && exit 1 || exit 0)
        working-directory: app-front

  front-lint:
    name: (front) lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: false

      - name: Install NodeJS
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: "24"

      - name: Install dependencies
        working-directory: app-front
        run: npm ci

      - name: Run lint
        working-directory: app-front
        run: npm run lint

  front-smoke:
    needs: [front-lint, front-audit]
    name: (front) smoke tests
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: false

      - name: Install NodeJS
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: "24"

      - name: Install dependencies
        working-directory: app-front
        run: npm ci

      - name: Run build
        working-directory: app-front
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ vars.API_ROOT_URL }}

  zizmor:
    name: (chore) GHA security
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for upload-sarif (used by zizmor-action) to upload SARIF files.
      contents: read # Only needed for private repos. Needed to clone the repo.
      actions: read # Only needed for private repos. Needed for upload-sarif to read workflow run info.
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@e639db99335bc9038abc0e066dfcd72e23d26fb4 # v0.3.0

  release:
    name: (chore) release
    runs-on: ubuntu-latest
    needs:
      - api-lint
      - api-unit
      - api-integration
      - api-e2e
      - front-audit
      - front-lint
      - front-smoke
      - zizmor
    permissions:
      contents: read
      actions: read # required by semantic-release
      issues: write # required by semantic-release
      security-events: write # required by semantic-release
      pull-requests: read # required by semantic-release
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: false # otherwise, the token used is GITHUB_TOKEN, instead of your personal token
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@9cc899c47e6841430bbaedb43de1560a568dfd16
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_RELEASE }}
