name: 'Release'

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false # otherwise, the token used is GITHUB_TOKEN, instead of your personal token
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v5
        with:
          branches: |
            [
              'main'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_RELEASE }}